Hooks:PostHook(MoneyTweakData, "init", "money shits", function (self, tweak_data)
local pro_job = Global.game_settings and Global.game_settings.one_down
local difficulty = Global.game_settings and Global.game_settings.difficulty or "normal"
local difficulty_index = tweak_data:difficulty_to_index(difficulty)
local pro_job_multiplier = 2

	self.offshore_rate = 0.50
	self.mandatory_mult = 0.50

  -- increase the money you get from the card cash shit.
	self.loot_drop_cash = { cash10 = 100000, cash20 = 150000, cash30 = 200000, cash40 = 250000, cash50 = 300000, cash60 = 350000, cash70 = 400000, 
                          cash80 = 450000, cash90 = 500000, cash100 = 600000, cash_preorder = 800000 }
	
	-- tweak loose cash depending on difficulty or pro job.
	if difficulty_index <= 2 then
		if pro_job then
		self.small_loot.money_bundle = 1000 * pro_job_multiplier
		self.small_loot.money_bundle_value = 10000 * pro_job_multiplier
		self.small_loot.ring_band = 1954 * pro_job_multiplier
		self.small_loot.diamondheist_vault_bust = 900 * pro_job_multiplier
		self.small_loot.diamondheist_vault_diamond = 1150 * pro_job_multiplier
		self.small_loot.diamondheist_big_diamond = 1150 * pro_job_multiplier
		self.small_loot.mus_small_artifact = 700 * pro_job_multiplier
		self.small_loot.value_gold = 3000 * pro_job_multiplier
		self.small_loot.gen_atm = 23000 * pro_job_multiplier
		self.small_loot.special_deposit_box = 3500 * pro_job_multiplier
		self.small_loot.slot_machine_payout = 25000 * pro_job_multiplier
		self.small_loot.vault_loot_chest = 570 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_chest = 610 * pro_job_multiplier
		self.small_loot.vault_loot_banknotes = 500 * pro_job_multiplier
		self.small_loot.vault_loot_silver = 540 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_collection = 650 * pro_job_multiplier
		self.small_loot.vault_loot_trophy = 690 * pro_job_multiplier
		self.small_loot.money_wrap_single_bundle_vscaled = 385 * pro_job_multiplier
		self.small_loot.spawn_bucket_of_money = 20000 * pro_job_multiplier
		self.small_loot.vault_loot_gold = 2500 * pro_job_multiplier
		self.small_loot.vault_loot_cash = 1200 * pro_job_multiplier
		self.small_loot.vault_loot_coins = 800 * pro_job_multiplier
		self.small_loot.vault_loot_ring = 300 * pro_job_multiplier
		self.small_loot.vault_loot_jewels = 600 * pro_job_multiplier
		self.small_loot.vault_loot_macka = 1 * pro_job_multiplier
		self.small_loot.federali_medal = 769 * pro_job_multiplier
	else
		self.small_loot.money_bundle = 1000
		self.small_loot.money_bundle_value = 10000
		self.small_loot.ring_band = 1954
		self.small_loot.diamondheist_vault_bust = 900
		self.small_loot.diamondheist_vault_diamond = 1150
		self.small_loot.diamondheist_big_diamond = 1150
		self.small_loot.mus_small_artifact = 700
		self.small_loot.value_gold = 3000
		self.small_loot.gen_atm = 23000
		self.small_loot.special_deposit_box = 3500
		self.small_loot.slot_machine_payout = 25000
		self.small_loot.vault_loot_chest = 570
		self.small_loot.vault_loot_diamond_chest = 610
		self.small_loot.vault_loot_banknotes = 500
		self.small_loot.vault_loot_silver = 540
		self.small_loot.vault_loot_diamond_collection = 650
		self.small_loot.vault_loot_trophy = 690
		self.small_loot.money_wrap_single_bundle_vscaled = 385
		self.small_loot.spawn_bucket_of_money = 20000
		self.small_loot.vault_loot_gold = 2500
		self.small_loot.vault_loot_cash = 1200
		self.small_loot.vault_loot_coins = 800
		self.small_loot.vault_loot_ring = 300
		self.small_loot.vault_loot_jewels = 600
		self.small_loot.vault_loot_macka = 1
		self.small_loot.federali_medal = 769
	end
	elseif difficulty_index == 3 then
		if pro_job then
		self.small_loot.money_bundle = 1000 * pro_job_multiplier
		self.small_loot.money_bundle_value = 10000 * pro_job_multiplier
		self.small_loot.ring_band = 1954 * pro_job_multiplier
		self.small_loot.diamondheist_vault_bust = 1800 * pro_job_multiplier
		self.small_loot.diamondheist_vault_diamond = 2300 * pro_job_multiplier
		self.small_loot.diamondheist_big_diamond = 2300 * pro_job_multiplier
		self.small_loot.mus_small_artifact = 1450 * pro_job_multiplier
		self.small_loot.value_gold = 3000 * pro_job_multiplier
		self.small_loot.gen_atm = 46000 * pro_job_multiplier
		self.small_loot.special_deposit_box = 3500 * pro_job_multiplier
		self.small_loot.slot_machine_payout = 50000 * pro_job_multiplier
		self.small_loot.vault_loot_chest = 1150 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_chest = 1250 * pro_job_multiplier
		self.small_loot.vault_loot_banknotes = 1000 * pro_job_multiplier
		self.small_loot.vault_loot_silver = 1100 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_collection = 1300 * pro_job_multiplier
		self.small_loot.vault_loot_trophy = 1400 * pro_job_multiplier
		self.small_loot.money_wrap_single_bundle_vscaled = 775 * pro_job_multiplier
		self.small_loot.spawn_bucket_of_money = 40000 * pro_job_multiplier
		self.small_loot.vault_loot_gold = 5000 * pro_job_multiplier
		self.small_loot.vault_loot_cash = 2500 * pro_job_multiplier
		self.small_loot.vault_loot_coins = 1500 * pro_job_multiplier
		self.small_loot.vault_loot_ring = 750 * pro_job_multiplier
		self.small_loot.vault_loot_jewels = 1200 * pro_job_multiplier
		self.small_loot.vault_loot_macka = 1 * pro_job_multiplier
		self.small_loot.federali_medal = 1538 * pro_job_multiplier
	else
		self.small_loot.money_bundle = 1000
		self.small_loot.money_bundle_value = 10000
		self.small_loot.ring_band = 1954
		self.small_loot.diamondheist_vault_bust = 1800
		self.small_loot.diamondheist_vault_diamond = 2300
		self.small_loot.diamondheist_big_diamond = 2300
		self.small_loot.mus_small_artifact = 1450
		self.small_loot.value_gold = 3000
		self.small_loot.gen_atm = 46000
		self.small_loot.special_deposit_box = 3500
		self.small_loot.slot_machine_payout = 50000
		self.small_loot.vault_loot_chest = 1150
		self.small_loot.vault_loot_diamond_chest = 1250
		self.small_loot.vault_loot_banknotes = 1000
		self.small_loot.vault_loot_silver = 1100
		self.small_loot.vault_loot_diamond_collection = 1300
		self.small_loot.vault_loot_trophy = 1400
		self.small_loot.money_wrap_single_bundle_vscaled = 775
		self.small_loot.spawn_bucket_of_money = 40000
		self.small_loot.vault_loot_gold = 5000
		self.small_loot.vault_loot_cash = 2500
		self.small_loot.vault_loot_coins = 1500
		self.small_loot.vault_loot_ring = 750
		self.small_loot.vault_loot_jewels = 1200
		self.small_loot.vault_loot_macka = 1
		self.small_loot.federali_medal = 1538
	end
	elseif difficulty_index == 4 then
		if pro_job then
		self.small_loot.money_bundle = 1000 * pro_job_multiplier
		self.small_loot.money_bundle_value = 10000 * pro_job_multiplier
		self.small_loot.ring_band = 1954 * pro_job_multiplier
		self.small_loot.diamondheist_vault_bust = 4500 * pro_job_multiplier
		self.small_loot.diamondheist_vault_diamond = 5750 * pro_job_multiplier
		self.small_loot.diamondheist_big_diamond = 5750 * pro_job_multiplier
		self.small_loot.mus_small_artifact = 3600 * pro_job_multiplier
		self.small_loot.value_gold = 3000 * pro_job_multiplier
		self.small_loot.gen_atm = 115000 * pro_job_multiplier
		self.small_loot.special_deposit_box = 3500 * pro_job_multiplier
		self.small_loot.slot_machine_payout = 125000 * pro_job_multiplier
		self.small_loot.vault_loot_chest = 2900 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_chest = 3100 * pro_job_multiplier
		self.small_loot.vault_loot_banknotes = 2500 * pro_job_multiplier
		self.small_loot.vault_loot_silver = 2700 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_collection = 3300 * pro_job_multiplier
		self.small_loot.vault_loot_trophy = 3500 * pro_job_multiplier
		self.small_loot.money_wrap_single_bundle_vscaled = 1950 * pro_job_multiplier
		self.small_loot.spawn_bucket_of_money = 100000 * pro_job_multiplier
		self.small_loot.vault_loot_gold = 11500 * pro_job_multiplier
		self.small_loot.vault_loot_cash = 5775 * pro_job_multiplier
		self.small_loot.vault_loot_coins = 4000 * pro_job_multiplier
		self.small_loot.vault_loot_ring = 1750 * pro_job_multiplier
		self.small_loot.vault_loot_jewels = 3000 * pro_job_multiplier
		self.small_loot.vault_loot_macka = 1 * pro_job_multiplier
		self.small_loot.federali_medal = 3838 * pro_job_multiplier
	else
		self.small_loot.money_bundle = 1000
		self.small_loot.money_bundle_value = 10000
		self.small_loot.ring_band = 1954
		self.small_loot.diamondheist_vault_bust = 4500
		self.small_loot.diamondheist_vault_diamond = 5750
		self.small_loot.diamondheist_big_diamond = 5750
		self.small_loot.mus_small_artifact = 3600
		self.small_loot.value_gold = 3000
		self.small_loot.gen_atm = 115000
		self.small_loot.special_deposit_box = 3500
		self.small_loot.slot_machine_payout = 125000
		self.small_loot.vault_loot_chest = 2900
		self.small_loot.vault_loot_diamond_chest = 3100
		self.small_loot.vault_loot_banknotes = 2500
		self.small_loot.vault_loot_silver = 2700
		self.small_loot.vault_loot_diamond_collection = 3300
		self.small_loot.vault_loot_trophy = 3500
		self.small_loot.money_wrap_single_bundle_vscaled = 1950
		self.small_loot.spawn_bucket_of_money = 100000
		self.small_loot.vault_loot_gold = 11500
		self.small_loot.vault_loot_cash = 5775
		self.small_loot.vault_loot_coins = 4000
		self.small_loot.vault_loot_ring = 1750
		self.small_loot.vault_loot_jewels = 3000
		self.small_loot.vault_loot_macka = 1
		self.small_loot.federali_medal = 3838
	end
	elseif difficulty_index == 5 then
		if pro_job then
		self.small_loot.money_bundle = 1000 * pro_job_multiplier
		self.small_loot.money_bundle_value = 10000 * pro_job_multiplier
		self.small_loot.ring_band = 1954 * pro_job_multiplier
		self.small_loot.diamondheist_vault_bust = 9000 * pro_job_multiplier
		self.small_loot.diamondheist_vault_diamond = 11500 * pro_job_multiplier
		self.small_loot.diamondheist_big_diamond = 11500 * pro_job_multiplier
		self.small_loot.mus_small_artifact = 7000 * pro_job_multiplier
		self.small_loot.value_gold = 3000 * pro_job_multiplier
		self.small_loot.gen_atm = 230000 * pro_job_multiplier
		self.small_loot.special_deposit_box = 3500 * pro_job_multiplier
		self.small_loot.slot_machine_payout = 250000 * pro_job_multiplier
		self.small_loot.vault_loot_chest = 5800 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_chest = 6200 * pro_job_multiplier
		self.small_loot.vault_loot_banknotes = 5000 * pro_job_multiplier
		self.small_loot.vault_loot_silver = 5400 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_collection = 6500 * pro_job_multiplier
		self.small_loot.vault_loot_trophy = 6900 * pro_job_multiplier
		self.small_loot.money_wrap_single_bundle_vscaled = 3800 * pro_job_multiplier
		self.small_loot.spawn_bucket_of_money = 200000 * pro_job_multiplier
		self.small_loot.vault_loot_gold = 23000 * pro_job_multiplier
		self.small_loot.vault_loot_cash = 11500 * pro_job_multiplier
		self.small_loot.vault_loot_coins = 8000 * pro_job_multiplier
		self.small_loot.vault_loot_ring = 3500 * pro_job_multiplier
		self.small_loot.vault_loot_jewels = 5775 * pro_job_multiplier
		self.small_loot.vault_loot_macka = 1 * pro_job_multiplier
		self.small_loot.federali_medal = 7692 * pro_job_multiplier
	else
		self.small_loot.money_bundle = 1000
		self.small_loot.money_bundle_value = 10000
		self.small_loot.ring_band = 1954
		self.small_loot.diamondheist_vault_bust = 9000
		self.small_loot.diamondheist_vault_diamond = 11500
		self.small_loot.diamondheist_big_diamond = 11500
		self.small_loot.mus_small_artifact = 7000
		self.small_loot.value_gold = 3000
		self.small_loot.gen_atm = 230000
		self.small_loot.special_deposit_box = 3500
		self.small_loot.slot_machine_payout = 250000
		self.small_loot.vault_loot_chest = 5800
		self.small_loot.vault_loot_diamond_chest = 6200
		self.small_loot.vault_loot_banknotes = 5000
		self.small_loot.vault_loot_silver = 5400
		self.small_loot.vault_loot_diamond_collection = 6500
		self.small_loot.vault_loot_trophy = 6900
		self.small_loot.money_wrap_single_bundle_vscaled = 3800
		self.small_loot.spawn_bucket_of_money = 200000
		self.small_loot.vault_loot_gold = 23000
		self.small_loot.vault_loot_cash = 11500
		self.small_loot.vault_loot_coins = 8000
		self.small_loot.vault_loot_ring = 3500
		self.small_loot.vault_loot_jewels = 5775
		self.small_loot.vault_loot_macka = 1
		self.small_loot.federali_medal = 7692
	end
	elseif difficulty_index == 6 then
		if pro_job then
		self.small_loot.money_bundle = 1000 * pro_job_multiplier
		self.small_loot.money_bundle_value = 10000 * pro_job_multiplier
		self.small_loot.ring_band = 1954 * pro_job_multiplier
		self.small_loot.diamondheist_vault_bust = 12000 * pro_job_multiplier
		self.small_loot.diamondheist_vault_diamond = 15000 * pro_job_multiplier
		self.small_loot.diamondheist_big_diamond = 15000 * pro_job_multiplier
		self.small_loot.mus_small_artifact = 9500 * pro_job_multiplier
		self.small_loot.value_gold = 3000 * pro_job_multiplier
		self.small_loot.gen_atm = 300000 * pro_job_multiplier
		self.small_loot.special_deposit_box = 3500 * pro_job_multiplier
		self.small_loot.slot_machine_payout = 325000 * pro_job_multiplier
		self.small_loot.vault_loot_chest = 7500 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_chest = 8000 * pro_job_multiplier
		self.small_loot.vault_loot_banknotes = 6500 * pro_job_multiplier
		self.small_loot.vault_loot_silver = 7000 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_collection = 8500 * pro_job_multiplier
		self.small_loot.vault_loot_trophy = 9000 * pro_job_multiplier
		self.small_loot.money_wrap_single_bundle_vscaled = 5000 * pro_job_multiplier
		self.small_loot.spawn_bucket_of_money = 260000 * pro_job_multiplier
		self.small_loot.vault_loot_gold = 30000 * pro_job_multiplier
		self.small_loot.vault_loot_cash = 15000 * pro_job_multiplier
		self.small_loot.vault_loot_coins = 10500 * pro_job_multiplier
		self.small_loot.vault_loot_ring = 4500 * pro_job_multiplier
		self.small_loot.vault_loot_jewels = 7500 * pro_job_multiplier
		self.small_loot.vault_loot_macka = 1 * pro_job_multiplier
		self.small_loot.federali_medal = 11000 * pro_job_multiplier
	else
		self.small_loot.money_bundle = 1000
		self.small_loot.money_bundle_value = 10000
		self.small_loot.ring_band = 1954
		self.small_loot.diamondheist_vault_bust = 12000
		self.small_loot.diamondheist_vault_diamond = 15000
		self.small_loot.diamondheist_big_diamond = 15000
		self.small_loot.mus_small_artifact = 9500
		self.small_loot.value_gold = 3000
		self.small_loot.gen_atm = 300000
		self.small_loot.special_deposit_box = 3500
		self.small_loot.slot_machine_payout = 325000
		self.small_loot.vault_loot_chest = 7500
		self.small_loot.vault_loot_diamond_chest = 8000
		self.small_loot.vault_loot_banknotes = 6500
		self.small_loot.vault_loot_silver = 7000
		self.small_loot.vault_loot_diamond_collection = 8500
		self.small_loot.vault_loot_trophy = 9000
		self.small_loot.money_wrap_single_bundle_vscaled = 5000
		self.small_loot.spawn_bucket_of_money = 260000
		self.small_loot.vault_loot_gold = 30000
		self.small_loot.vault_loot_cash = 15000
		self.small_loot.vault_loot_coins = 10500
		self.small_loot.vault_loot_ring = 4500
		self.small_loot.vault_loot_jewels = 7500
		self.small_loot.vault_loot_macka = 1
		self.small_loot.federali_medal = 11000
	end
	elseif difficulty_index == 7 then
		if pro_job then
		self.small_loot.money_bundle = 1000 * pro_job_multiplier
		self.small_loot.money_bundle_value = 10000 * pro_job_multiplier
		self.small_loot.ring_band = 1954 * pro_job_multiplier
		self.small_loot.diamondheist_vault_bust = 12000 * pro_job_multiplier
		self.small_loot.diamondheist_vault_diamond = 15000 * pro_job_multiplier
		self.small_loot.diamondheist_big_diamond = 15000 * pro_job_multiplier
		self.small_loot.mus_small_artifact = 9500 * pro_job_multiplier
		self.small_loot.value_gold = 3000 * pro_job_multiplier
		self.small_loot.gen_atm = 300000 * pro_job_multiplier
		self.small_loot.special_deposit_box = 3500 * pro_job_multiplier
		self.small_loot.slot_machine_payout = 325000 * pro_job_multiplier
		self.small_loot.vault_loot_chest = 7500 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_chest = 8000 * pro_job_multiplier
		self.small_loot.vault_loot_banknotes = 6500 * pro_job_multiplier
		self.small_loot.vault_loot_silver = 7000 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_collection = 8500 * pro_job_multiplier
		self.small_loot.vault_loot_trophy = 9000 * pro_job_multiplier
		self.small_loot.money_wrap_single_bundle_vscaled = 5000 * pro_job_multiplier
		self.small_loot.spawn_bucket_of_money = 260000 * pro_job_multiplier
		self.small_loot.vault_loot_gold = 30000 * pro_job_multiplier
		self.small_loot.vault_loot_cash = 15000 * pro_job_multiplier
		self.small_loot.vault_loot_coins = 10500 * pro_job_multiplier
		self.small_loot.vault_loot_ring = 4500 * pro_job_multiplier
		self.small_loot.vault_loot_jewels = 7500 * pro_job_multiplier
		self.small_loot.vault_loot_macka = 1 * pro_job_multiplier
		self.small_loot.federali_medal = 11000 * pro_job_multiplier
	else
		self.small_loot.money_bundle = 1000
		self.small_loot.money_bundle_value = 10000
		self.small_loot.ring_band = 1954
		self.small_loot.diamondheist_vault_bust = 12000
		self.small_loot.diamondheist_vault_diamond = 15000
		self.small_loot.diamondheist_big_diamond = 15000
		self.small_loot.mus_small_artifact = 9500
		self.small_loot.value_gold = 3000
		self.small_loot.gen_atm = 300000
		self.small_loot.special_deposit_box = 3500
		self.small_loot.slot_machine_payout = 325000
		self.small_loot.vault_loot_chest = 7500
		self.small_loot.vault_loot_diamond_chest = 8000
		self.small_loot.vault_loot_banknotes = 6500
		self.small_loot.vault_loot_silver = 7000
		self.small_loot.vault_loot_diamond_collection = 8500
		self.small_loot.vault_loot_trophy = 9000
		self.small_loot.money_wrap_single_bundle_vscaled = 5000
		self.small_loot.spawn_bucket_of_money = 260000
		self.small_loot.vault_loot_gold = 30000
		self.small_loot.vault_loot_cash = 15000
		self.small_loot.vault_loot_coins = 10500
		self.small_loot.vault_loot_ring = 4500
		self.small_loot.vault_loot_jewels = 7500
		self.small_loot.vault_loot_macka = 1
		self.small_loot.federali_medal = 11000
	end
	else
		if pro_job then
		self.small_loot.money_bundle = 1000 * pro_job_multiplier
		self.small_loot.money_bundle_value = 100000 * pro_job_multiplier
		self.small_loot.ring_band = 1954 * pro_job_multiplier
		self.small_loot.diamondheist_vault_bust = 12000 * pro_job_multiplier
		self.small_loot.diamondheist_vault_diamond = 15000 * pro_job_multiplier
		self.small_loot.diamondheist_big_diamond = 15000 * pro_job_multiplier
		self.small_loot.mus_small_artifact = 9500 * pro_job_multiplier
		self.small_loot.value_gold = 3000 * pro_job_multiplier
		self.small_loot.gen_atm = 300000 * pro_job_multiplier
		self.small_loot.special_deposit_box = 3500 * pro_job_multiplier
		self.small_loot.slot_machine_payout = 325000 * pro_job_multiplier
		self.small_loot.vault_loot_chest = 7500 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_chest = 8000 * pro_job_multiplier
		self.small_loot.vault_loot_banknotes = 6500 * pro_job_multiplier
		self.small_loot.vault_loot_silver = 7000 * pro_job_multiplier
		self.small_loot.vault_loot_diamond_collection = 8500 * pro_job_multiplier
		self.small_loot.vault_loot_trophy = 9000 * pro_job_multiplier
		self.small_loot.money_wrap_single_bundle_vscaled = 5000 * pro_job_multiplier
		self.small_loot.spawn_bucket_of_money = 260000 * pro_job_multiplier
		self.small_loot.vault_loot_gold = 30000 * pro_job_multiplier
		self.small_loot.vault_loot_cash = 15000 * pro_job_multiplier
		self.small_loot.vault_loot_coins = 10500 * pro_job_multiplier
		self.small_loot.vault_loot_ring = 4500 * pro_job_multiplier
		self.small_loot.vault_loot_jewels = 7500 * pro_job_multiplier
		self.small_loot.vault_loot_macka = 1 * pro_job_multiplier
		self.small_loot.federali_medal = 11000 * pro_job_multiplier
	else
		self.small_loot.money_bundle = 1000
		self.small_loot.money_bundle_value = 10000
		self.small_loot.ring_band = 1954
		self.small_loot.diamondheist_vault_bust = 12000
		self.small_loot.diamondheist_vault_diamond = 15000
		self.small_loot.diamondheist_big_diamond = 15000
		self.small_loot.mus_small_artifact = 9500
		self.small_loot.value_gold = 3000
		self.small_loot.gen_atm = 300000
		self.small_loot.special_deposit_box = 3500
		self.small_loot.slot_machine_payout = 325000
		self.small_loot.vault_loot_chest = 7500
		self.small_loot.vault_loot_diamond_chest = 8000
		self.small_loot.vault_loot_banknotes = 6500
		self.small_loot.vault_loot_silver = 7000
		self.small_loot.vault_loot_diamond_collection = 8500
		self.small_loot.vault_loot_trophy = 9000
		self.small_loot.money_wrap_single_bundle_vscaled = 5000
		self.small_loot.spawn_bucket_of_money = 260000
		self.small_loot.vault_loot_gold = 30000
		self.small_loot.vault_loot_cash = 15000
		self.small_loot.vault_loot_coins = 10500
		self.small_loot.vault_loot_ring = 4500
		self.small_loot.vault_loot_jewels = 7500
		self.small_loot.vault_loot_macka = 1
		self.small_loot.federali_medal = 11000
		end
	end
end)
